name = "AffineRayleighOptimization"
uuid = "afc0e0ae-cd0a-41ee-b0f5-7950de095d62"
authors = ["William Samuelson <william.samuelson@gmail.com> and contributors"]
version = "2.0.0"

[deps]
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[weakdeps]
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"

[extensions]
AffineRayleighOptimizationLinearSolveExt = "LinearSolve"

[compat]
Aqua = "0.8"
JET = "0.9"
KrylovKit = "0.8"
LinearAlgebra = "1"
LinearMaps = "3"
LinearSolve = "2"
Random = "1"
SciMLBase = "2"
SparseArrays = "1"
Test = "1"
TestItemRunner = "1.0"
TestItems = "1.0"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner", "Random", "LinearSolve", "SparseArrays", "Aqua", "JET"]
